Table 4.2.1: Age of all clients in treatment

In [1]:
from gssutils import *

if is_interactive():
    scraper = Scraper('https://www.gov.uk/government/collections/alcohol-and-drug-misuse-and-treatment-statistics')
    scraper.select_dataset(title=lambda x: x.startswith('Substance misuse treatment for adults'), latest=True)
    tabs = {tab.name: tab for tab in scraper.distribution(title=lambda x: x.startswith('Data tables')).as_databaker()}

In [2]:
tab = tabs['Table 4.2.1']

https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/752515/AdultSubstanceMisuseNDTMSDataTables2017-18.xlsx

In [3]:
cell = tab.filter('Age')
cell.assert_one()
observations = tab.filter('n').fill(DOWN).is_not_blank().is_not_whitespace()
age = cell.expand(DOWN).is_not_blank().is_not_whitespace()
Clients = cell.expand(RIGHT).is_not_blank().is_not_whitespace()
Dimensions = [
            HDim(age,'Treatment group',DIRECTLY,LEFT),
            HDim(Clients,'Clients in treatment',CLOSEST,LEFT),
            HDimConst('Measure Type','Count'),
            HDimConst('Unit','Clients in treatment'),
            HDimConst('Period', '2018-03-31T00:00:00/P1Y'),
            HDimConst('Basis of treatment','age')
            ]

In [4]:
c1 = ConversionSegment(observations, Dimensions, processTIMEUNIT=True)
if is_interactive():
    savepreviewhtml(c1)

In [5]:
new_table = c1.topandas()

In [6]:
import numpy as np
new_table['OBS'].replace('', np.nan, inplace=True)
new_table.dropna(subset=['OBS'], inplace=True)
new_table.rename(columns={'OBS': 'Value'}, inplace=True)
new_table['Value'] = new_table['Value'].astype(int)
new_table['Value'] = new_table['Value'].map(lambda x:''
                                  if (x == '-')
                                  else int(x))

In [7]:
new_table['Treatment group'] = new_table['Treatment group'].map(
    lambda x: {
        'Total' : 'All years' 
        }.get(x, x))

In [8]:
new_table['Clients in treatment'] = new_table['Clients in treatment'].map(
    lambda x: {
        'Total' : 'All Clients' 
        }.get(x, x))

In [9]:
new_table = new_table[['Period','Basis of treatment','Treatment group','Clients in treatment','Measure Type','Value','Unit']]

In [10]:
new_table

,Period,Basis of treatment,Treatment group,Clients in treatment,Measure Type,Value,Unit
0,2018-03-31T00:00:00/P1Y,age,18,Opiate,Count,116,Clients in treatment
1,2018-03-31T00:00:00/P1Y,age,18,Non-opiate only,Count,948,Clients in treatment
2,2018-03-31T00:00:00/P1Y,age,18,Non-opiate and Alcohol,Count,721,Clients in treatment
3,2018-03-31T00:00:00/P1Y,age,18,Alcohol only,Count,204,Clients in treatment
4,2018-03-31T00:00:00/P1Y,age,18,All Clients,Count,1989,Clients in treatment
5,2018-03-31T00:00:00/P1Y,age,19,Opiate,Count,184,Clients in treatment
6,2018-03-31T00:00:00/P1Y,age,19,Non-opiate only,Count,829,Clients in treatment
7,2018-03-31T00:00:00/P1Y,age,19,Non-opiate and Alcohol,Count,483,Clients in treatment
8,2018-03-31T00:00:00/P1Y,age,19,Alcohol only,Count,176,Clients in treatment
9,2018-03-31T00:00:00/P1Y,age,19,All Clients,Count,1672,Clients in treatment
10,2018-03-31T00:00:00/P1Y,age,20-24,Opiate,Count,2772,Clients in treatment
11,2018-03-31T00:00:00/P1Y,age,20-24,Non-opiate only,Count,4361,Clients in treatment
12,2018-03-31T00:00:00/P1Y,age,20-24,Non-opiate and Alcohol,Count,3122,Clients in treatment
13,2018-03-31T00:00:00/P1Y,age,20-24,Alcohol only,Count,1824,Clients in treatment
14,2018-03-31T00:00:00/P1Y,age,20-24,All Clients,Count,12079,Clients in treatment
15,2018-03-31T00:00:00/P1Y,age,25-29,Opiate,Count,10114,Clients in treatment
16,2018-03-31T00:00:00/P1Y,age,25-29,Non-opiate only,Count,5001,Clients in treatment
17,2018-03-31T00:00:00/P1Y,age,25-29,Non-opiate and Alcohol,Count,4698,Clients in treatment
18,2018-03-31T00:00:00/P1Y,age,25-29,Alcohol only,Count,4516,Clients in treatment
19,2018-03-31T00:00:00/P1Y,age,25-29,All Clients,Count,24329,Clients in treatment
20,2018-03-31T00:00:00/P1Y,age,30-34,Opiate,Count,21067,Clients in treatment
21,2018-03-31T00:00:00/P1Y,age,30-34,Non-opiate only,Count,4337,Clients in treatment
22,2018-03-31T00:00:00/P1Y,age,30-34,Non-opiate and Alcohol,Count,5106,Clients in treatment
23,2018-03-31T00:00:00/P1Y,age,30-34,Alcohol only,Count,7184,Clients in treatment
24,2018-03-31T00:00:00/P1Y,age,30-34,All Clients,Count,37694,Clients in treatment
25,2018-03-31T00:00:00/P1Y,age,35-39,Opiate,Count,32263,Clients in treatment
26,2018-03-31T00:00:00/P1Y,age,35-39,Non-opiate only,Count,3234,Clients in treatment
27,2018-03-31T00:00:00/P1Y,age,35-39,Non-opiate and Alcohol,Count,4431,Clients in treatment
28,2018-03-31T00:00:00/P1Y,age,35-39,Alcohol only,Count,9369,Clients in treatment
29,2018-03-31T00:00:00/P1Y,age,35-39,All Clients,Count,49297,Clients in treatment
...,...,...,...,...,...,...,...
40,2018-03-31T00:00:00/P1Y,age,50-54,Opiate,Count,13612,Clients in treatment
41,2018-03-31T00:00:00/P1Y,age,50-54,Non-opiate only,Count,827,Clients in treatment
42,2018-03-31T00:00:00/P1Y,age,50-54,Non-opiate and Alcohol,Count,1770,Clients in treatment
43,2018-03-31T00:00:00/P1Y,age,50-54,Alcohol only,Count,11602,Clients in treatment
44,2018-03-31T00:00:00/P1Y,age,50-54,All Clients,Count,27811,Clients in treatment
45,2018-03-31T00:00:00/P1Y,age,55-59,Opiate,Count,5784,Clients in treatment
46,2018-03-31T00:00:00/P1Y,age,55-59,Non-opiate only,Count,408,Clients in treatment
47,2018-03-31T00:00:00/P1Y,age,55-59,Non-opiate and Alcohol,Count,869,Clients in treatment
48,2018-03-31T00:00:00/P1Y,age,55-59,Alcohol only,Count,8463,Clients in treatment
49,2018-03-31T00:00:00/P1Y,age,55-59,All Clients,Count,15524,Clients in treatment
50,2018-03-31T00:00:00/P1Y,age,60-64,Opiate,Count,2350,Clients in treatment
51,2018-03-31T00:00:00/P1Y,age,60-64,Non-opiate only,Count,165,Clients in treatment
52,2018-03-31T00:00:00/P1Y,age,60-64,Non-opiate and Alcohol,Count,295,Clients in treatment
53,2018-03-31T00:00:00/P1Y,age,60-64,Alcohol only,Count,4761,Clients in treatment
54,2018-03-31T00:00:00/P1Y,age,60-64,All Clients,Count,7571,Clients in treatment
55,2018-03-31T00:00:00/P1Y,age,65-69,Opiate,Count,850,Clients in treatment
56,2018-03-31T00:00:00/P1Y,age,65-69,Non-opiate only,Count,113,Clients in treatment
57,2018-03-31T00:00:00/P1Y,age,65-69,Non-opiate and Alcohol,Count,68,Clients in treatment
58,2018-03-31T00:00:00/P1Y,age,65-69,Alcohol only,Count,2579,Clients in treatment
59,2018-03-31T00:00:00/P1Y,age,65-69,All Clients,Count,3610,Clients in treatment
60,2018-03-31T00:00:00/P1Y,age,70+,Opiate,Count,233,Clients in treatment
61,2018-03-31T00:00:00/P1Y,age,70+,Non-opiate only,Count,132,Clients in treatment
62,2018-03-31T00:00:00/P1Y,age,70+,Non-opiate and Alcohol,Count,20,Clients in treatment
63,2018-03-31T00:00:00/P1Y,age,70+,Alcohol only,Count,1605,Clients in treatment
64,2018-03-31T00:00:00/P1Y,age,70+,All Clients,Count,1990,Clients in treatment
65,2018-03-31T00:00:00/P1Y,age,All years,Opiate,Count,141189,Clients in treatment
66,2018-03-31T00:00:00/P1Y,age,All years,Non-opiate only,Count,23730,Clients in treatment
67,2018-03-31T00:00:00/P1Y,age,All years,Non-opiate and Alcohol,Count,27684,Clients in treatment
68,2018-03-31T00:00:00/P1Y,age,All years,Alcohol only,Count,75787,Clients in treatment
69,2018-03-31T00:00:00/P1Y,age,All years,All Clients,Count,268390,Clients in treatment