Table 4.12.3: Clients' children receiving early help or in contact with children's social care

In [1]:
from gssutils import *

if is_interactive():
    scraper = Scraper('https://www.gov.uk/government/collections/alcohol-and-drug-misuse-and-treatment-statistics')
    scraper.select_dataset(title=lambda x: x.startswith('Substance misuse treatment for adults'), latest=True)
    tabs = {tab.name: tab for tab in scraper.distribution(title=lambda x: x.startswith('Data tables')).as_databaker()}

In [2]:
tab = tabs['Table 4.12.3']

https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/752515/AdultSubstanceMisuseNDTMSDataTables2017-18.xlsx

In [3]:
cell = tab.filter("Help received or in contact with children's social care")
cell.assert_one()
observations = tab.filter('n').fill(DOWN).is_not_blank().is_not_whitespace()
helps = cell.expand(DOWN).is_not_blank().is_not_whitespace()
Clients = cell.expand(RIGHT).is_not_blank().is_not_whitespace()
Dimensions = [
            HDim(helps,'Treatment group',DIRECTLY,LEFT),
            HDim(Clients,'Clients in treatment',CLOSEST,LEFT),
            HDimConst('Measure Type','Count'),
            HDimConst('Unit','Children in treatment'),
            HDimConst('Period', '2018-03-31T00:00:00/P1Y'),
            HDimConst('Basis of treatment','children care')
            ]

In [4]:
c1 = ConversionSegment(observations, Dimensions, processTIMEUNIT=True)
if is_interactive():
    savepreviewhtml(c1)

In [5]:
new_table = c1.topandas()

In [6]:
import numpy as np
new_table['OBS'].replace('', np.nan, inplace=True)
new_table.dropna(subset=['OBS'], inplace=True)
new_table.rename(columns={'OBS': 'Value'}, inplace=True)
new_table['Value'] = new_table['Value'].astype(int)
new_table['Value'] = new_table['Value'].map(lambda x:''
                                  if (x == '-')
                                  else int(x))

In [7]:
new_table["Treatment group"] = new_table["Treatment group"].map(
    lambda x: {
        'Total' : 'All types of care' 
        }.get(x, x))

In [8]:
def user_perc(x):
    
    if x == None:
        return 'All inclusice missing'
    else:
        return x
    
new_table["Treatment group"] = new_table.apply(lambda row: user_perc(row["Treatment group"]), axis = 1)

In [9]:
new_table['Clients in treatment'] = new_table['Clients in treatment'].map(
    lambda x: {
        'Total' : 'All Clients',
        }.get(x, x))

In [10]:
new_table = new_table[['Period','Basis of treatment','Treatment group','Clients in treatment','Measure Type','Value','Unit']]

In [11]:
new_table

,Period,Basis of treatment,Treatment group,Clients in treatment,Measure Type,Value,Unit
0,2018-03-31T00:00:00/P1Y,children care,Early help,Opiates,Count,299,Children in treatment
1,2018-03-31T00:00:00/P1Y,children care,Early help,Non-opiates only,Count,343,Children in treatment
2,2018-03-31T00:00:00/P1Y,children care,Early help,Alcohol & non-opiates,Count,278,Children in treatment
3,2018-03-31T00:00:00/P1Y,children care,Early help,Alcohol only,Count,779,Children in treatment
4,2018-03-31T00:00:00/P1Y,children care,Early help,All Clients,Count,1699,Children in treatment
5,2018-03-31T00:00:00/P1Y,children care,Child in need,Opiates,Count,390,Children in treatment
6,2018-03-31T00:00:00/P1Y,children care,Child in need,Non-opiates only,Count,410,Children in treatment
7,2018-03-31T00:00:00/P1Y,children care,Child in need,Alcohol & non-opiates,Count,311,Children in treatment
8,2018-03-31T00:00:00/P1Y,children care,Child in need,Alcohol only,Count,734,Children in treatment
9,2018-03-31T00:00:00/P1Y,children care,Child in need,All Clients,Count,1845,Children in treatment
10,2018-03-31T00:00:00/P1Y,children care,Child protection plan,Opiates,Count,1070,Children in treatment
11,2018-03-31T00:00:00/P1Y,children care,Child protection plan,Non-opiates only,Count,1125,Children in treatment
12,2018-03-31T00:00:00/P1Y,children care,Child protection plan,Alcohol & non-opiates,Count,780,Children in treatment
13,2018-03-31T00:00:00/P1Y,children care,Child protection plan,Alcohol only,Count,1434,Children in treatment
14,2018-03-31T00:00:00/P1Y,children care,Child protection plan,All Clients,Count,4409,Children in treatment
15,2018-03-31T00:00:00/P1Y,children care,Looked after child,Opiates,Count,1287,Children in treatment
16,2018-03-31T00:00:00/P1Y,children care,Looked after child,Non-opiates only,Count,460,Children in treatment
17,2018-03-31T00:00:00/P1Y,children care,Looked after child,Alcohol & non-opiates,Count,368,Children in treatment
18,2018-03-31T00:00:00/P1Y,children care,Looked after child,Alcohol only,Count,573,Children in treatment
19,2018-03-31T00:00:00/P1Y,children care,Looked after child,All Clients,Count,2688,Children in treatment
20,2018-03-31T00:00:00/P1Y,children care,No early help,Opiates,Count,15534,Children in treatment
21,2018-03-31T00:00:00/P1Y,children care,No early help,Non-opiates only,Count,5237,Children in treatment
22,2018-03-31T00:00:00/P1Y,children care,No early help,Alcohol & non-opiates,Count,6493,Children in treatment
23,2018-03-31T00:00:00/P1Y,children care,No early help,Alcohol only,Count,17383,Children in treatment
24,2018-03-31T00:00:00/P1Y,children care,No early help,All Clients,Count,44647,Children in treatment
25,2018-03-31T00:00:00/P1Y,children care,All types of care,Opiates,Count,18580,Children in treatment
26,2018-03-31T00:00:00/P1Y,children care,All types of care,Non-opiates only,Count,7575,Children in treatment
27,2018-03-31T00:00:00/P1Y,children care,All types of care,Alcohol & non-opiates,Count,8230,Children in treatment
28,2018-03-31T00:00:00/P1Y,children care,All types of care,Alcohol only,Count,20903,Children in treatment
29,2018-03-31T00:00:00/P1Y,children care,All types of care,All Clients,Count,55288,Children in treatment
30,2018-03-31T00:00:00/P1Y,children care,Missing,Opiates,Count,3005,Children in treatment
31,2018-03-31T00:00:00/P1Y,children care,Missing,Non-opiates only,Count,1053,Children in treatment
32,2018-03-31T00:00:00/P1Y,children care,Missing,Alcohol & non-opiates,Count,1129,Children in treatment
33,2018-03-31T00:00:00/P1Y,children care,Missing,Alcohol only,Count,3970,Children in treatment
34,2018-03-31T00:00:00/P1Y,children care,Missing,All Clients,Count,9157,Children in treatment
35,2018-03-31T00:00:00/P1Y,children care,All types of care,Opiates,Count,21585,Children in treatment
36,2018-03-31T00:00:00/P1Y,children care,All types of care,Non-opiates only,Count,8628,Children in treatment
37,2018-03-31T00:00:00/P1Y,children care,All types of care,Alcohol & non-opiates,Count,9359,Children in treatment
38,2018-03-31T00:00:00/P1Y,children care,All types of care,Alcohol only,Count,24873,Children in treatment
39,2018-03-31T00:00:00/P1Y,children care,All types of care,All Clients,Count,64445,Children in treatment